Traceback (most recent call last):
  File "/home/3 semester kandidat/ML Operations/dtu_mlops/s4_debugging_and_logging/exercise_files/vae_mnist_working.py", line 104, in <module>
    model = Model(Encoder=encoder, Decoder=decoder).to(DEVICE)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/root/anaconda3/envs/ML-OPS/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx